# Using Checkout Action

name: hello-world
on:
  push:
  workflow_dispatch:

jobs:
  Using-Checkout:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: hello world jobs
       run: echo "hello world"
       shell: bash


    
